accounts/urls.py
from django.urls import path
from .views import signup_view,login_view,logout_view



app_name='accounts'
urlpatterns = [
    path('signup/',signup_view,name='signup'),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
]

todoapp/urls.py
from django.urls import path
from .views import HomeView, todo_item_delete,todo_list_view,todo_item_create,todo_item_delete



app_name='todoapp'
urlpatterns = [
    path('',HomeView,name='home'),
    path('list/',todo_list_view,name='todo_list'),
    path('create/',todo_item_create,name='todo_item_create'),
    path('<id>/delete',todo_item_delete,name='todo_item_delete'),

]

todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
    path('accounts/',include('accounts.urls')),

]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class TodoItem(models.Model):
    work=models.CharField(max_length=100)
    checked=models.BooleanField(default=False)
    owner=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    date=models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.work

todoapp/forms.py
from dataclasses import field
from django import forms
from .models import TodoItem


class TodoItemForm(forms.ModelForm):
    class Meta:
        model=TodoItem
        fields=['work','date']

accounts/views.py
import django
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm,  UserCreationForm
from django.contrib.auth import login,logout

# Create your views here.

def signup_view(request):
    if request.method=='POST':
         form=UserCreationForm(request.POST)
         if form.is_valid():
             user=form.save()
             login(request, user)

             return redirect('/')
    form=UserCreationForm

    return render(request,'accounts/signup.html',{'form':form})



def login_view(request):
    if request.method=='POST':
         form=AuthenticationForm(data=request.POST)
         if form.is_valid():
             user=form.get_user()
             login(request,user)
             return redirect('/')

    form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method=='POST':
        logout(request)

        return redirect('/')

todoapp/views.py
from ast import Try
from glob import escape
from django.shortcuts import render,redirect

from .forms import TodoItemForm
from .models import TodoItem
from django.contrib.auth.decorators import login_required
# Create your views here.

def HomeView(request):
    return render(request,'todoapp/home.html')


@login_required(login_url='/accounts/login')
def todo_list_view(request):
    user=request.user
    query=TodoItem.objects.filter(owner=user)
    if request.method=='POST':
        print(request.POST)
        checked_list=request.POST.getlist('checked')
        checked_list=[int(i) for i in checked_list]
        for todo_item in query:
            if todo_item.id in checked_list:
                TodoItem.objects.filter(id=todo_item.id).update(checked=True)
            else:
                TodoItem.objects.filter(id=todo_item.id).update(checked=False)

        return redirect('/list')

    todo_list_len=len(query)

    return render(request,'todoapp/todo_list.html',{'todolist':query,'todo_list_len':todo_list_len})



@login_required(login_url='/accounts/login')
def todo_item_create(request):
    user=request.user
    if request.method=='POST':
        form=TodoItemForm(request.POST)
        if form.is_valid():
           instance=form.save() #instance=form.save(commit=False)
           instance.owner=user
           instance.save()
        #    return redirect('/list')
           return redirect('todoapp:todo_list')

    form=TodoItemForm()

    return render(request,'todoapp/create_todo_item.html',{'form':form})

@login_required(login_url='/accounts/login')
def todo_item_delete(request,id):
    try:
        item=TodoItem.objects.get(id=id)
    except:
        return redirect('todoapp:todo_list')

    if item.owner==request.user:
        item.delete()
        return redirect('todoapp:todo_list')
    else:
        return redirect('todoapp:todo_list')

accounts/templates/accounts/login.html
{% extends 'base.html'%}
{% block title %} Login {% endblock %}
{% block content %}
<form method="POST">
    {%csrf_token%}
    {{form}}
    <button type="submit">login</button>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html'%}
{% block title %} signup {% endblock %}
{% block content %}
<form method="POST">
    {%csrf_token%}
    {{form}}
    <button type="submit">signup</button>
</form>
{% endblock %}

todoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}

  <!-- <link rel="stylesheet" href="path/to/fontawesome.min.css"> -->
  <!-- <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css"
    integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
    integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">


  <!-- <link rel="stylesheet" href="{% static 'css/style.css'%}"> this form is toaly *TRUE* for run css file -->
  <link rel="stylesheet" type="text/css" href="{% static 'todoapp/style.css'%}"> <!--this form is toaly *false for run css file -->
  <!-- its not work befor becuase i had error in fontawesome.min.css and i see that in inspect-> consol browser -->
  
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ToDo App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=" {% url 'todoapp:todo_list' %}">ToDo List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">ContactUs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Accounts</a>
          </li>
        </ul>
      </div>
      {% if user.is_authenticated %}
      <form action='{% url "accounts:logout" %}' method="POST">
        {%csrf_token%}

        <button class="btn btn-link">logout</button>
      </form>
      {% else %}
      <a href='{% url "accounts:login" %}'>login</a> /<a href='{% url "accounts:signup" %}'>signup</a>

      {% endif %}

    </div>
  </nav>



  <div class="container">
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
  </div>
</body>

</html>

todoapp/templates/todoapp/create_todo_item.html
{% extends 'base.html'%}
{% block title %} create todo list {% endblock %}
{% block content %}

<div class="container create-form-container">
    <h1>create</h1>
    <form class="create-todo-form" action="" method="POST">
        <div class="input-container">
            <label for="">{{form.work.label}}</label>
            <input class="helper-text" required type="text" name="work" id="id_work">
            <p class="helper-text">please write your todo job</p>
        </div>
        <div class="input-container">
            <label for="">{{form.date.label}}</label>
            <input class="helper-text"  type="datetime-local" name="date" id="id_date">
            <p class="helper-text">here you can pick a date and time for your todo job</p>
        </div>
     
            <button class="btn btn-primary" type="submit">Add</button>
            {%csrf_token%}
        
    </form>
</div>


{% endblock %}

todoapp/templates/todoapp/home.html
{% extends 'base.html'%}
{% block title %} todo list App {% endblock %}
{% block content %}

<h1>Home Template </h1>
{% endblock %}

todoapp/templates/todoapp/todo_list.html
{% extends 'base.html'%}
{% block title %} todo list {% endblock %}
{% block content %}
{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static '/todoapp/style.css'%}"> -->
<!-- <link rel="stylesheet" href="{% static 'css/style.css'%}"> -->

<div class="list-container">
    {% if todo_list_len == 0 %}
    <div>
        <h3> Nothing is here ...</h3>
        <a href="{% url 'todoapp:todo_item_create'%}"> You can Add jobs todo from here :)</a>
    </div>
    {% else %}
    <div class="todo-list-container">
        <form method="POST" action=" {% url 'todoapp:todo_list'%}" id="todo-list-form">
            <div class="todo-list">

                <ul class="list-group">
                    {% for todoitem in todolist %}

                    <li class="list-group-item todo-item">
                        <div class="todo-item-content ">
                            {% if todoitem.checked %}
                            <input class="check-input form-check-input job-done-input " type="checkbox" name="checked"
                                checked value="{{todoitem.id}}" aria-label="...">
                            <div class="job-done-text job-text">

                                <h6>{{todoitem.work}}</h6>
                                <p>{{todoitem.date}}</p>
                            </div>
                            {% else %}
                            <input class="check-input form-check-input me-1" type="checkbox" name="checked"
                                value="{{todoitem.id}}" aria-label="...">

                            <div class="job-undone-text job-text">
                                <h6>{{todoitem.work}}</h6>
                                <p>{{todoitem.date}}</p>
                            </div>
                            {% endif %}
                        </div>
                        <div class="todo-item-action">
                            <a class="btn btn-danger" href="{% url 'todoapp:todo_item_delete' todoitem.id %}"><i
                                    class="bi bi-trash"></i></a>


                            <a class="btn btn-secondary" href="{% url 'todoapp:todo_item_delete' todoitem.id %}"><i
                                    class="bi bi-pencil"></i></a>


                        </div>

                    </li>

                    {% endfor%}
                </ul>
            </div>
            {% csrf_token %}
            <button class="btn btn-primary" id="print_paper"><i class="bi bi-printer"></i></button>
            <a href="/create">create new task</a>
        </form>

    </div>

    {% endif %}


</div>
<script>
    let check_input = document.getElementsByName('checked')
    let form = document.getElementById('todo-list-form')
    let print_btn = document.getElementById('print_paper')

    check_input.forEach(element => {
        element.addEventListener('click', function () {
            form.submit()
        })
    })
    print_btn.addEventListener('click', function () {
        print()
    })


</script>

{% endblock %}